const items = [
  { 
    id:`001`,
    image: `product/1.webp`,
    Rating: {
      star: 4.3,
      ratingCount: 22900,
    },
    company: `Mast & Harbour`,
    itemName: `Men Slim Fit Causal Sustainb`,
    currentPrice: 554,
    originalPrice: 2099,
    discount: 73,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:80,
  },
  {id:`002`,
    image: `product/2.webp`,
    Rating: {
      star: 4.3,
      ratingCount: 3200,
    },
    company: `Campous Sutra`,
    itemName: `Spread collar Casual Shirt`,
    currentPrice: 759,
    originalPrice: 1899,
    discount: 60,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:85,
  },
  {
    id:`003`,
    image: `product/3.webp`,
    Rating: {
      star: 4.3,
      ratingCount: 6400,
    },
    company: `THE BEAR  HOUSE`,
    itemName: `Slim Fit Casual Shirt`,
    currentPrice: 1122,
    originalPrice: 2495,
    discount: 55,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:54,
  },
  {
    id:`004`,
    image:`product/4.webp`,
    Rating: {
      star: 4.2,
      ratingCount: 27600,
    },
    company: `HIGHLANDER`,
    itemName: `Slim Fit Casual Shirt`,
    currentPrice: 506,
    originalPrice: 1299,
    discount:   61,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:56,
  },
  {
    id:`05`,
    image: `product/5.webp`,
    Rating: {
      star: 0,
      ratingCount: 0,
    },
    company: `BYFORD by pantaloons`,
    itemName: `Slim Fit Opaque Party Shirt`,
    currentPrice: 803,
    originalPrice: 1199,
    discount: 33,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:50,
  },
  {
    id:`006`,
    image: `product/6.webp`,
    Rating: {
      star: 4.2,
      ratingCount: 1200,
    },
    company: `Roadstar`,
    itemName: `Men Checked Casual Shirt`,
    currentPrice: 545,
    originalPrice: 1399,
    discount: 61,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:120,
  },
  {
    id:`007`,
    image: `product/7.webp`,
    Rating: {
      star: 4.2,
      ratingCount: 9400,
    },
    company: `Roadstar`,
    itemName: `Men Cotton Casual Shirt`,
    currentPrice: 953,
    originalPrice: 1799,
    discount: 47,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:23,
  },
  {
    id:`008`,
    image: `product/8.webp`,
    Rating: {
      star: 4.5,
      ratingCount: 1400,
    },
    company: `xyz`,
    itemName: `xyz`,
    currentPrice: 0,
    originalPrice: 0,
    discount: 0,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:56,
  },
  {
    id:`009`,
    image: `product/9.webp`,
    Rating: {
      star: 3.9,
      ratingCount: 9200,
    },
    company: `Powerlook`,
    itemName: `Tartan Checked Casual Shirt`,
    currentPrice: 989,
    originalPrice: 1799,
    discount: 45,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:20,
  },
  {
    id:`010`,
    image: `product/10.webp`,
    Rating: {
      star: 0,
      ratingCount: 0,
    },
    company: `Powerlook`,
    itemName: `Slim Casual Shirt`,
    currentPrice: 1500,
    originalPrice: 3000,
    discount: 50,
    delivery_time:`10days`,
    seller_name:`Ram`,
    coupon:70,
  },
];
